# 应用名称
spring:
  application:
    name: baselog

# 应用服务 WEB 访问端口
server:
  port: 8083

# Actuator Web 访问端口
management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: always



# 自定义配置
baselog:
  packageurl: "execution(public * fun.gengzi.baselog.test..*.*(..))"


